version: '2'
services:
  # The Application
  app:
    container_name: app
#    build: ./app
    image: albertalvarezbruned/laravel:app
    working_dir: /var/www
    volumes:
      - appdata:/var/www
#      - "./www:/var/www"
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    container_name: web
#    build: ./web
    image: albertalvarezbruned/laravel:web
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8888:80

  cron:
    container_name: cron
#    build: ./cron_tests
    image: albertalvarezbruned/laravel:cron_tests
    working_dir: /var/www
    volumes_from:
      - app

  # The Database
  database:
    container_name: database
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
#      - "./bbdd:/var/lib/mysql"
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata:
  appdata:
